-- Autogenerated file. Changes may be lost!
return [[ [
    {
        "name": "Nothing",
        "desc": [
            "How did you even manage to play this?"
        ],
        "base_chips": 0.0,
        "base_mult": 0.0,
        "level_chips": 1.0,
        "level_mult": 0.0,
        "eval": [
            {
                "pattern": [],
                "options": {}
            }
        ],
        "order_offset": 0,
        "author": "TamerSoup625",
        "joker_mult": 4.0,
        "joker_chips": 25.0,
        "joker_xmult": 1.001,
        "planet_name": " "
    },
    {
        "name": "Just Plain Lucky",
        "desc": [
            "1 in 1000 chance to get this hand",
            "(modifiable by Oops! All 6s and similar effects)"
        ],
        "base_chips": 777.0,
        "base_mult": 77.0,
        "level_chips": 77.0,
        "level_mult": 7.0,
        "eval": [
            {
                "pattern": [],
                "options": {}
            }
        ],
        "author": "MathIsFun_"
    }
] ]]